"""initial schema (autogen)

Revision ID: 20a324271419
Revises: 6fcaaa8f51ab
Create Date: 2026-02-21 20:12:55.041983

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '20a324271419'
down_revision: Union[str, Sequence[str], None] = '6fcaaa8f51ab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sites',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('timezone', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('batteries',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('site_id', sa.UUID(), nullable=True),
    sa.Column('capacity_kwh', sa.Float(), nullable=False),
    sa.Column('max_charge_kw', sa.Float(), nullable=False),
    sa.Column('max_discharge_kw', sa.Float(), nullable=False),
    sa.Column('min_soc_pct', sa.Float(), nullable=False),
    sa.Column('max_soc_pct', sa.Float(), nullable=False),
    sa.Column('provider_type', sa.String(), nullable=False),
    sa.Column('provider_config', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('forecast_runs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('site_id', sa.UUID(), nullable=True),
    sa.Column('run_time', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tariffs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('site_id', sa.UUID(), nullable=True),
    sa.Column('import_type', sa.String(), nullable=False),
    sa.Column('export_type', sa.String(), nullable=False),
    sa.Column('config_json', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('forecast_intervals',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('forecast_run_id', sa.UUID(), nullable=True),
    sa.Column('period_end', sa.DateTime(), nullable=False),
    sa.Column('solar_kwh', sa.Float(), nullable=False),
    sa.Column('demand_kwh', sa.Float(), nullable=False),
    sa.Column('import_price', sa.Float(), nullable=False),
    sa.Column('export_price', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['forecast_run_id'], ['forecast_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('optimisation_runs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('site_id', sa.UUID(), nullable=True),
    sa.Column('forecast_run_id', sa.UUID(), nullable=True),
    sa.Column('initial_soc_kwh', sa.Float(), nullable=False),
    sa.Column('total_cost_estimate', sa.Float(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['forecast_run_id'], ['forecast_runs.id'], ),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('optimisation_intervals',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('optimisation_run_id', sa.UUID(), nullable=True),
    sa.Column('period_end', sa.DateTime(), nullable=False),
    sa.Column('charge_kwh', sa.Float(), nullable=True),
    sa.Column('discharge_kwh', sa.Float(), nullable=True),
    sa.Column('soc_kwh', sa.Float(), nullable=True),
    sa.Column('grid_import_kwh', sa.Float(), nullable=True),
    sa.Column('grid_export_kwh', sa.Float(), nullable=True),
    sa.Column('cost', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['optimisation_run_id'], ['optimisation_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('schedules',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('optimisation_run_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('sent_at', sa.DateTime(), nullable=True),
    sa.Column('provider_response', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['optimisation_run_id'], ['optimisation_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('schedules')
    op.drop_table('optimisation_intervals')
    op.drop_table('optimisation_runs')
    op.drop_table('forecast_intervals')
    op.drop_table('tariffs')
    op.drop_table('forecast_runs')
    op.drop_table('batteries')
    op.drop_table('sites')
    # ### end Alembic commands ###
