"""add demand_forecast table

Revision ID: 2ef446747003
Revises: 778bcdeeff36
Create Date: 2026-02-21 21:08:09.447711

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2ef446747003'
down_revision: Union[str, Sequence[str], None] = '778bcdeeff36'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('demand_forecast',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('period_end', sa.DateTime(), nullable=False),
    sa.Column('demand_kwh', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('period_end')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('demand_forecast')
    # ### end Alembic commands ###
