"""add agile_rates table

Revision ID: 778bcdeeff36
Revises: ce1077876727
Create Date: 2026-02-21 20:57:56.236103

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '778bcdeeff36'
down_revision: Union[str, Sequence[str], None] = 'ce1077876727'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('solcast_forecast',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('period_end', sa.DateTime(), nullable=False),
    sa.Column('solar_kwh', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('period_end')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('solcast_forecast')
    # ### end Alembic commands ###
