"""add demand_forecast table

Revision ID: 891dce8612d2
Revises: 02cac6b6f6e7
Create Date: 2026-02-21 22:13:32.205761

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '891dce8612d2'
down_revision: Union[str, Sequence[str], None] = '02cac6b6f6e7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('historic_demand',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('period_end', sa.DateTime(), nullable=False),
    sa.Column('variable', sa.String(), nullable=True),
    sa.Column('unit', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('value', sa.Float(), nullable=True),
    sa.Column('time', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('period_end')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('historic_demand')
    # ### end Alembic commands ###
