"""add agile_rates table

Revision ID: ce1077876727
Revises: 20a324271419
Create Date: 2026-02-21 20:22:48.375803

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ce1077876727'
down_revision: Union[str, Sequence[str], None] = '20a324271419'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agile_rates',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('period_end', sa.DateTime(), nullable=False),
    sa.Column('import_price', sa.Float(), nullable=False),
    sa.Column('export_price', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('period_end')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('agile_rates')
    # ### end Alembic commands ###
